spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: <facebook client id>
            clientSecret: <facebook client secret>
            scope: email, public_profile
  jms:
    template:
      default-destination: tacocloud.order.queue

#  rabbitmq:
#    template:
#      exchange: tacocloud.order
#      routing-key: kitchens.central
#  data:
#    rest:
#      base-path: /data-api

server:
  port: 8443
  ssl:
    key-store: file:src/main/resources/mykeys.jks
    key-store-password: ibragim
    key-password: ibragim

tacocloud:
  email:
    host: https://mail.google.com/mail/u/0/#inbox
    mailbox: Google Inbox
    username: grinnosse@gmail.com
    password: Gsm19972789sanemiGsm
    pollRate: 30000